// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: balances.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const decrementBalance = `-- name: DecrementBalance :one
UPDATE balances
SET available  = available  - $2,
    total_paid = total_paid + $2
WHERE creator_id = $1
  AND available >= $2
RETURNING creator_id, available, total_earned, total_paid
`

type DecrementBalanceParams struct {
	CreatorID pgtype.UUID    `json:"creator_id"`
	Available pgtype.Numeric `json:"available"`
}

func (q *Queries) DecrementBalance(ctx context.Context, arg DecrementBalanceParams) (Balance, error) {
	row := q.db.QueryRow(ctx, decrementBalance, arg.CreatorID, arg.Available)
	var i Balance
	err := row.Scan(
		&i.CreatorID,
		&i.Available,
		&i.TotalEarned,
		&i.TotalPaid,
	)
	return i, err
}

const getBalance = `-- name: GetBalance :one
SELECT creator_id, available, total_earned, total_paid FROM balances
WHERE creator_id = $1
`

func (q *Queries) GetBalance(ctx context.Context, creatorID pgtype.UUID) (Balance, error) {
	row := q.db.QueryRow(ctx, getBalance, creatorID)
	var i Balance
	err := row.Scan(
		&i.CreatorID,
		&i.Available,
		&i.TotalEarned,
		&i.TotalPaid,
	)
	return i, err
}

const upsertBalance = `-- name: UpsertBalance :one
INSERT INTO balances (creator_id, available, total_earned, total_paid)
VALUES ($1, $2, $2, 0)
ON CONFLICT (creator_id) DO UPDATE
SET available    = balances.available    + EXCLUDED.available,
    total_earned = balances.total_earned + EXCLUDED.total_earned
RETURNING creator_id, available, total_earned, total_paid
`

type UpsertBalanceParams struct {
	CreatorID pgtype.UUID    `json:"creator_id"`
	Available pgtype.Numeric `json:"available"`
}

func (q *Queries) UpsertBalance(ctx context.Context, arg UpsertBalanceParams) (Balance, error) {
	row := q.db.QueryRow(ctx, upsertBalance, arg.CreatorID, arg.Available)
	var i Balance
	err := row.Scan(
		&i.CreatorID,
		&i.Available,
		&i.TotalEarned,
		&i.TotalPaid,
	)
	return i, err
}
