// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Balance struct {
	CreatorID   pgtype.UUID    `json:"creator_id"`
	Available   pgtype.Numeric `json:"available"`
	TotalEarned pgtype.Numeric `json:"total_earned"`
	TotalPaid   pgtype.Numeric `json:"total_paid"`
}

type Payout struct {
	ID          pgtype.UUID        `json:"id"`
	CreatorID   pgtype.UUID        `json:"creator_id"`
	Amount      pgtype.Numeric     `json:"amount"`
	Status      string             `json:"status"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

type Transaction struct {
	ID        pgtype.UUID        `json:"id"`
	FanID     pgtype.UUID        `json:"fan_id"`
	CreatorID pgtype.UUID        `json:"creator_id"`
	TierID    pgtype.UUID        `json:"tier_id"`
	Amount    pgtype.Numeric     `json:"amount"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
