// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payouts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPayoutsByCreator = `-- name: CountPayoutsByCreator :one
SELECT COUNT(*) FROM payouts
WHERE creator_id = $1
`

func (q *Queries) CountPayoutsByCreator(ctx context.Context, creatorID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPayoutsByCreator, creatorID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertPayout = `-- name: InsertPayout :one
INSERT INTO payouts (creator_id, amount, status, completed_at)
VALUES ($1, $2, 'completed', now())
RETURNING id, creator_id, amount, status, completed_at
`

type InsertPayoutParams struct {
	CreatorID pgtype.UUID    `json:"creator_id"`
	Amount    pgtype.Numeric `json:"amount"`
}

func (q *Queries) InsertPayout(ctx context.Context, arg InsertPayoutParams) (Payout, error) {
	row := q.db.QueryRow(ctx, insertPayout, arg.CreatorID, arg.Amount)
	var i Payout
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Amount,
		&i.Status,
		&i.CompletedAt,
	)
	return i, err
}

const listPayoutsByCreator = `-- name: ListPayoutsByCreator :many
SELECT id, creator_id, amount, status, completed_at FROM payouts
WHERE creator_id = $1
ORDER BY completed_at DESC
LIMIT $2 OFFSET $3
`

type ListPayoutsByCreatorParams struct {
	CreatorID pgtype.UUID `json:"creator_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) ListPayoutsByCreator(ctx context.Context, arg ListPayoutsByCreatorParams) ([]Payout, error) {
	rows, err := q.db.Query(ctx, listPayoutsByCreator, arg.CreatorID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payout
	for rows.Next() {
		var i Payout
		if err := rows.Scan(
			&i.ID,
			&i.CreatorID,
			&i.Amount,
			&i.Status,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
