// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: revenue.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRevenue = `-- name: GetRevenue :one
SELECT COALESCE(SUM(amount), 0)::NUMERIC(10,2) AS total
FROM transactions
WHERE creator_id = $1
  AND ($2::TIMESTAMPTZ IS NULL OR created_at >= $2)
  AND ($3::TIMESTAMPTZ IS NULL OR created_at <= $3)
`

type GetRevenueParams struct {
	CreatorID pgtype.UUID        `json:"creator_id"`
	Column2   pgtype.Timestamptz `json:"column_2"`
	Column3   pgtype.Timestamptz `json:"column_3"`
}

func (q *Queries) GetRevenue(ctx context.Context, arg GetRevenueParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getRevenue, arg.CreatorID, arg.Column2, arg.Column3)
	var total pgtype.Numeric
	err := row.Scan(&total)
	return total, err
}

const getRevenueByTier = `-- name: GetRevenueByTier :many
SELECT
    tier_id,
    COUNT(*)::INT               AS count,
    SUM(amount)::NUMERIC(10,2)  AS amount
FROM transactions
WHERE creator_id = $1
  AND ($2::TIMESTAMPTZ IS NULL OR created_at >= $2)
  AND ($3::TIMESTAMPTZ IS NULL OR created_at <= $3)
GROUP BY tier_id
`

type GetRevenueByTierParams struct {
	CreatorID pgtype.UUID        `json:"creator_id"`
	Column2   pgtype.Timestamptz `json:"column_2"`
	Column3   pgtype.Timestamptz `json:"column_3"`
}

type GetRevenueByTierRow struct {
	TierID pgtype.UUID    `json:"tier_id"`
	Count  int32          `json:"count"`
	Amount pgtype.Numeric `json:"amount"`
}

func (q *Queries) GetRevenueByTier(ctx context.Context, arg GetRevenueByTierParams) ([]GetRevenueByTierRow, error) {
	rows, err := q.db.Query(ctx, getRevenueByTier, arg.CreatorID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRevenueByTierRow
	for rows.Next() {
		var i GetRevenueByTierRow
		if err := rows.Scan(&i.TierID, &i.Count, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
