// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTransactionsByFan = `-- name: CountTransactionsByFan :one
SELECT COUNT(*) FROM transactions
WHERE fan_id = $1
`

func (q *Queries) CountTransactionsByFan(ctx context.Context, fanID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTransactionsByFan, fanID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertTransaction = `-- name: InsertTransaction :one
INSERT INTO transactions (fan_id, creator_id, tier_id, amount, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, fan_id, creator_id, tier_id, amount, status, created_at
`

type InsertTransactionParams struct {
	FanID     pgtype.UUID    `json:"fan_id"`
	CreatorID pgtype.UUID    `json:"creator_id"`
	TierID    pgtype.UUID    `json:"tier_id"`
	Amount    pgtype.Numeric `json:"amount"`
	Status    string         `json:"status"`
}

func (q *Queries) InsertTransaction(ctx context.Context, arg InsertTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, insertTransaction,
		arg.FanID,
		arg.CreatorID,
		arg.TierID,
		arg.Amount,
		arg.Status,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.FanID,
		&i.CreatorID,
		&i.TierID,
		&i.Amount,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listTransactionsByFan = `-- name: ListTransactionsByFan :many
SELECT id, fan_id, creator_id, tier_id, amount, status, created_at FROM transactions
WHERE fan_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListTransactionsByFanParams struct {
	FanID  pgtype.UUID `json:"fan_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListTransactionsByFan(ctx context.Context, arg ListTransactionsByFanParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByFan, arg.FanID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.FanID,
			&i.CreatorID,
			&i.TierID,
			&i.Amount,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
